name: xtensor-python
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  # Host dependencies
  - xtensor>=0.25,<0.26
  - numpy
  - pybind11>=2.6.1,<3
  # Test dependencies
  - pytest

